### ISSUE TITLE
Support for "Access groups" in the ipRanges spec

### ISSUE THREAD

**Issue by psarossy** [BojanZelic/cloudflare-zero-trust-operator#123]
Cloudflare supports using access groups for IP address ranges, but the current CloudFlareAccessGroupRule definition does not support these as it expects as string only [code ref](https://github.com/BojanZelic/cloudflare-zero-trust-operator/blob/6fdb42f900ebf5d2642f116a9ed51681ead65505/api/v1alpha1/cloudflareaccessgroup_types.go#L51)

Would this be interesting to support? I'm thinking maybe adding an IPRangeGroup or so, so both structs are supported?

**Comment by BojanZelic** [comment]
Hi @psarossy 

Hmm, I'm not following, do you have more details of what you're trying to accomplish.

`IPRanges` should support a CIDR for multiple addresses if you want to target multiple ip's.
ex: https://github.com/BojanZelic/cloudflare-zero-trust-operator/blob/6fdb42f900ebf5d2642f116a9ed51681ead65505/README.md?plain=1#L92-L93


likewise you can define an [AccessGroup](https://github.com/BojanZelic/cloudflare-zero-trust-operator/blob/main/config/samples/CloudflareAccessGroup.yaml) with IP addresses and reference it using the accessGroups value param:
https://github.com/BojanZelic/cloudflare-zero-trust-operator/blob/6fdb42f900ebf5d2642f116a9ed51681ead65505/README.md?plain=1#L94-L95

**Comment by psarossy** [comment]
Apologies, turns out this was a user error due to Kustomize playing mind games and overriding the namespace specification in my access group definition, and it was creating the access group definition in a different namespace while ignoring the explicit definition...
